MOVED_LEFT = 'MOVED_LEFT'
MOVED_RIGHT = 'MOVED_RIGHT'
MOVED_UP = 'MOVED_UP'
MOVED_DOWN = 'MOVED_DOWN'
WAITED = 'WAITED'
INVALID_ACTION = 'INVALID_ACTION'

BOMB_DROPPED = 'BOMB_DROPPED'
BOMB_EXPLODED = 'BOMB_EXPLODED'

CRATE_DESTROYED = 'CRATE_DESTROYED'
COIN_FOUND = 'COIN_FOUND'
COIN_COLLECTED = 'COIN_COLLECTED'

KILLED_OPPONENT = 'KILLED_OPPONENT'
KILLED_SELF = 'KILLED_SELF'

GOT_KILLED = 'GOT_KILLED'
OPPONENT_ELIMINATED = 'OPPONENT_ELIMINATED'
SURVIVED_ROUND = 'SURVIVED_ROUND'

COOL = "COOL"
WARM = "WARM"
HOT = "HOT"
BOILING = "BOILING"
FRESHENED_UP = "FRESHENED_UP"

USELESS_BOMB = "USELESS_BOMB"
CRATE_COMBO = "CRATE_COMBO"

STEP_SURVIVED = "STEP_SURVIVED"
CRATE_POTENTIALLY_DESTROYED = "CRATE_POTENTIALLY_DESTROYED"

ENEMY_POTENTIALLY_KILLED = "ENEMY_POTENTIALLY_KILLED"
LAST_AGENT_STANDING = "LAST_AGENT_STANDING"

CLOSER_TO_ENEMY = "CLOSER_TO_ENEMY"
FURTHER_FROM_ENEMY = "FURTHER_FROM_ENEMY"
ENEMY_IN_DEAD_END = "ENEMY_IN_DEAD_END"
IN_DEAD_END = "IN_DEAD_END"